project_id = "nuzagorzqqggxlwxbosp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[auth]
enabled = true
port = 54324

[edge_functions]
enabled = true
port = 54325

[functions.onboarding-start]
verify_jwt = true

[functions.me-dashboard]
verify_jwt = true

[functions.card-actions]
verify_jwt = true