project_id = "pbfqdfipjnaqhoxhlitw"

# Phase 1 - Onboarding & Dashboard Management
[functions.onboarding-start]
verify_jwt = true

[functions.me-dashboard]
verify_jwt = true

[functions.cards-actions]
verify_jwt = true

# Phase 2 - Companies, Topics, Feeds
[functions.companies]
verify_jwt = true

[functions.topics] 
verify_jwt = true

[functions.feeds-autogenerate]
verify_jwt = true

[functions.fetch-rss]
verify_jwt = false

[functions.refresh-cards]
verify_jwt = false

# Phase 3 & 4 - Documents & KPIs
[functions.documents-sign-upload]
verify_jwt = true

[functions.documents-parse]
verify_jwt = true

[functions.kpis-import-xlsx]
verify_jwt = true

# Phase 5 - Briefing API
[functions.briefing-today]
verify_jwt = true

# Phase 6 - Enhanced Operations
[functions.fetch-rss-enhanced]
verify_jwt = false