// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbfqdfipjnaqhoxhlitw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBiZnFkZmlwam5hcWhveGhsaXR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTY0OTMsImV4cCI6MjA3MTM5MjQ5M30.Ms8WYvWheAgPYHZUVDWmE2PD6AMntoJe5Tom5HCsgwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});