// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuzagorzqqggxlwxbosp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51emFnb3J6cXFnZ3hsd3hib3NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODYzNTEsImV4cCI6MjA3MTM2MjM1MX0.kkPmqmVPcmZTwadoey5Aie37gg1P1UENXlFsbAKKt0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});